export default function getStudents() {
  return [
    { ID: 1, Name: "Aaron" },
    { ID: 2, Name: "Alfonso" },
    { ID: 3, Name: "Ava" },
    { ID: 4, Name: "Blake" },
    { ID: 5, Name: "Brett" },
    { ID: 6, Name: "Chris" },
    { ID: 7, Name: "Daniel" },
    { ID: 8, Name: "Daphne" },
    { ID: 9, Name: "Heidi" },
    { ID: 10, Name: "Jackson" },
    { ID: 11, Name: "Jacob" },
    { ID: 12, Name: "Jovanna" },
    { ID: 13, Name: "Julia" },
    { ID: 14, Name: "Kayla" },
    { ID: 15, Name: "Madison" },
    { ID: 16, Name: "Mary C." },
    { ID: 17, Name: "Mary W." },
    { ID: 18, Name: "Maylie" },
    { ID: 19, Name: "Nicole" },
    { ID: 20, Name: "Owen" },
    { ID: 21, Name: "Tara" },
  ];
}
